version: 0.2
   
phases:

  build:
    commands:
      - echo "******** Building site ********"
      - ls -la 
      - python create_page.py
      - mkdir site
      - cp index.html site/
      - aws s3 sync site/ s3://nc-state-fair-food-finder   
      - ls -la 


      - echo "******** Logging Build Event ********"
      - pwd
      - mkdir log
      - cd log
      - mkdir general_events
      - ls -la
      - cd general_events
      - ls -la
      - pwd
      - cd ..
      - cd ..
      - pwd
      - cp build_event_json.txt log/general_events/
      - aws s3 sync log/ s3://aws-s3-to-es     





