version: 0.2
   
phases:

  build:
    commands:
      - echo "******** Running tests ********"
      - cd tests
      - python unit_tests.py
      - cd ..

      - echo "******** Building site ********"
      - ls -la 
      - python create_page.py
      - aws s3 sync site_results/ s3://nc-state-fair-food-finder   
      - ls -la 


      - echo "******** Logging Build Event ********"
      - pwd
      - mkdir log
      - cd log
      - mkdir general_events
      - ls -la
      - cd general_events
      - ls -la
      - pwd
      - cd ..
      - cd ..
      - pwd
      - cp build_event_json.txt log/general_events/
      - aws s3 sync log/ s3://aws-s3-to-es     





