version: 0.2
   
phases:

  build:
    commands:
      - echo "******** Building Staging Jekyll site with drafts ********"

      - echo "******** Logging Build Event ********"
      - pwd
      - mkdir log
      - cd log
      - mkdir general_events
      - ls -la
      - cd general_events
      - ls -la
      - pwd
      - cd ..
      - cd ..
      - pwd
      - cp build_event_json.txt log/general_events/
      - aws s3 sync log/ s3://aws-s3-to-es     





